---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultimate-cicd-depoymeb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ultimate-cicd-app
  template:
    metadata:
      labels:
        app: ultimate-cicd-app
    spec:
      containers:
      - name: ultimate-cicd-container
        image: ridhwan90/ultimate-cicd:42884fb
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ultimate-cicd-service
spec:
  selector:
    app: ultimate-cicd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer